### ISSUE TITLE
安装时提示“请检查是否安装 Gboard”，然后失败

### ISSUE THREAD

**Issue by kailiu42** [entr0pia/gboard_dict_3#1]
一加8手机，Oxygen OS  IN2015_11_C.11（Android 12），Magisk 24.3，Gboard 11.4.07.422524001-release-arm64-v8a，beta版本也测试过。

安装本模块时，出现以下提示，无法完成安装：

![image](https://user-images.githubusercontent.com/358679/163905264-b48edb1e-af89-4f32-a143-b4ddebb06258.png)

**Comment by entr0pia** [comment]
看一下你设备上 `/data/data/com.google.android.inputmethod.latin` 目录存在吗

**Comment by kailiu42** [comment]
用Solid Explorer（root权限）和shell su，访问/data/data都只能看到两个目录。其中用Solid Explorer时提示“自Andriod 11以来，该应用程序对该目录的访问权限有限”。应该是和这个有关：

https://developer.android.com/about/versions/11/privacy/storage#other-private-dirs

能看到的两个目录是本应用自身的，和com.google.android.gms。

**Comment by entr0pia** [comment]
试一下新发布的 v2.0.3

另外, 用[质感文件](https://github.com/zhanghai/MaterialFiles)可以完整访问 `/data/data` 目录

**Comment by kailiu42** [comment]
可以成功安装了。但是打guangyu出不来“光遇”

**Comment by entr0pia** [comment]
要等上一两分钟

**Comment by kailiu42** [comment]
等了蛮久了。

**Comment by entr0pia** [comment]
我又测试了一下, 是能打出`光·遇`的

**Comment by kailiu42** [comment]
刚才把这个模块卸载了，看了下/data/data/com.google.android.inputmethod.latin/files目录，下面有个user_dict_3_3，6.6MB。模块内那个是11MB的。把这个文件删掉，然后又把模块装上了，重启。又看了下这个文件变成12.2MB了，再打了下有光遇了-_-

**Comment by liu-cool-cmd** [comment]
![Screenshot_20220422-223720_X-plore](https://user-images.githubusercontent.com/52557882/164736660-84f08f54-4ffa-42a0-9023-6344c1a08f5b.png)
![Screenshot_20220422-223230_Gboard](https://user-images.githubusercontent.com/52557882/164736742-5ef9be1d-da7b-4b70-b35b-918161b2d115.png)
![Screenshot_20220422-223129_😅](https://user-images.githubusercontent.com/52557882/164736763-d1914a84-faf8-4cc5-abc0-788e9a7fed3a.png)
我也遇到了这个问题，最新版本的，/data/data下没那个文件夹

**Comment by liu-cool-cmd** [comment]
修正，我有这个文件夹
![Screenshot_20220422-224231_R E 管理器](https://user-images.githubusercontent.com/52557882/164737604-14014368-45ed-43f0-a677-3e596768b4bd.png)
