### ISSUE TITLE
请求出一个没有简拼的版本

### ISSUE THREAD

**Issue by RavioliWonton** [entr0pia/gboard_dict_3#3]
Gborad版本：商店最新测试（11.8.05.446165824-beta-arm64-v8a）
模块版本：2.1.1

在实际使用时经常会出现需要选取助词单字“了”，“的”的时候，“就范”，“奋发”候选会抢排在第一个，非常影响输入体验，所以可以单独出一个只有全拼的版本吗？
（或者告诉我怎么编辑词库，我可以自己动手

**Comment by entr0pia** [comment]
`user_dict_3_3` 词库做不到. 因为无论双拼还是简拼, 都不是词库本身的工作, 而是 Gboard 对 `user_dict_3_3` 数据库的优化查询.

你可以试试 [CustomPinyinDictionary](https://github.com/wuhgit/CustomPinyinDictionary) 这个词库, 准确来说应该叫"自定义短语", 不过就只能用全拼了.

**Comment by RavioliWonton** [comment]
好的吧，我说我怎么不管是移除建议还是自定义短语都没有用，谢谢！
